### ISSUE TITLE
Perfboard version.

### ISSUE THREAD

**Issue by RevelRob** [digiblur/digiDryerMon#3]
First off, this is awesome. I got it to work with the breadboard and jumpers; however, as an idiot, I am trying to figure out how to recreate your perfboard version. Is there any way to possibly attach a picture of the Wemos attached to the perfboard version you made and possibly a picture of both sides of the created perfboard? Hopefully I have an "Ah Ha!" moment after seeing it.

Thanks so much for what you have contributed to the community! It is so appreciated.

**Comment by RevelRob** [comment]
After watching the video again, I heard you say that you use jumper wires to connect the board with the Wemos D1 Mini.
I wanted something cleaner; so I made it as follows:
I grabbed a Perf board set from Amazon and threw something together using some of the preformed jumpers, capacitor, resistors and a 3.5mm female jack connector that I got a long time ago:
![IMG_7151](https://user-images.githubusercontent.com/31980432/153810919-567324ec-e965-4502-ab86-351c7f7d1afe.jpg)
![IMG_7152](https://user-images.githubusercontent.com/31980432/153810921-1b29ed78-4df6-4662-b5c2-f9f0faba589f.jpg)
![IMG_7153](https://user-images.githubusercontent.com/31980432/153810922-16567488-a56d-41e0-945c-1419b072190f.jpg)

I got this USB drive awhile ago and it came with this neat magnetic case and some foam to hold the drive:
![IMG_7166](https://user-images.githubusercontent.com/31980432/153810325-57793ec4-2d57-4cbe-94c9-c02c086aef42.jpg)

I cut the foam piece a bit, tossed the board into the case, and drilled out some holes (One day, I will buy a 3D printer... one day):
![IMG_7154](https://user-images.githubusercontent.com/31980432/153811202-cb169172-2e3c-4653-99a0-6f4de500bf21.jpg)
![IMG_7155](https://user-images.githubusercontent.com/31980432/153811204-dc291dca-681c-4158-8686-603d02a29f2d.jpg)
![IMG_7156](https://user-images.githubusercontent.com/31980432/153811205-230ba022-cab4-4e25-ac32-5b02ba6c2caf.jpg)
![IMG_7157](https://user-images.githubusercontent.com/31980432/153811207-4e390fd5-c8dc-499e-9cd1-7b3aa450eccb.jpg)

The finished product:
![IMG_7158](https://user-images.githubusercontent.com/31980432/153811243-198e6632-0070-4b1c-b0da-7b9085b7953b.jpg)

Hooked up to the dryer:
![IMG_7163](https://user-images.githubusercontent.com/31980432/153811275-7a88774c-11fd-4db1-ba18-519769a246ab.jpg)
![IMG_7164](https://user-images.githubusercontent.com/31980432/153811278-68cc7252-86ae-42b7-aab7-076ea954a559.jpg)

I actually almost gave up because the plug goes in through the bottom of the non-removable back panel. I started pulling apart the dryer bit by bit where I was afraid I wouldn't be able to put it back together. I was at the point where I would have to remove the drum to get to where I could see the inside of the back panel. I decided it was time to turn back. Right before closing up this top panel; I thought, no way were these wires going to be pulling enough amperage to read anything. I was happily incorrect.

She works!
![IMG_7179](https://user-images.githubusercontent.com/31980432/153811305-98a077e8-6c6c-436c-a5ac-c0d56249e0c9.jpg)

I added a "cooling" notification; but it looks like the dryer dips to "cooling" amperage a few times before the final 10 min mark:
![IMG_7180](https://user-images.githubusercontent.com/31980432/153811417-9e845bae-eb38-4244-b0aa-722da0cf3a54.jpg)

Anyways. Thanks for this! I was my first time playing with an ESP development board besides flashing some sonoff devices. After this, I bought a bunch of Wemos and some ESP32's and have been amazed at the amount of things that can be done.

**Comment by digiblur** [comment]
Just happened to see this thread...Nice pics and execution of the device!  Thanks for sharing things.  Sounds like some of the various pieces of fun for trying to determine if the washing machine is running or not.  They are all different for sure.
